name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.9
          bundler-cache: true
      - name: RuboCop
        run: bundle exec rubocop

  rspec:
    runs-on: ubuntu-latest
    needs: rubocop
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.9
          bundler-cache: true
      - name: RSpec
        env:
          RAILS_ENV: test
        run: bundle exec rspec --format documentation
